// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiHogarConnect.API.Data;

#nullable disable

namespace ServiHogarConnect.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720042430_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiHogarConnect.API.Models.Calificacion", b =>
                {
                    b.Property<int>("IdCalificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCalificacion"));

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdProfesional")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("integer");

                    b.HasKey("IdCalificacion");

                    b.HasIndex("IdProfesional");

                    b.HasIndex("IdUsuario", "IdProfesional")
                        .IsUnique();

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("ServiHogarConnect.API.Models.CategoriaServicio", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriasServicio");
                });

            modelBuilder.Entity("ServiHogarConnect.API.Models.Cotizacion", b =>
                {
                    b.Property<int>("IdCotizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCotizacion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdProfesional")
                        .HasColumnType("integer");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioOfertado")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("TiempoEstimado")
                        .HasColumnType("text");

                    b.HasKey("IdCotizacion");

                    b.HasIndex("IdProfesional");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("ServiHogarConnect.API.Models.MensajeChat", b =>
                {
                    b.Property<int>("IdMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMensaje"));

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEmisor")
                        .HasColumnType("integer");

                    b.Property<int>("IdReceptor")
                        .HasColumnType("integer");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdMensaje");

                    b.HasIndex("IdReceptor");

                    b.HasIndex("IdEmisor", "IdReceptor", "FechaEnvio");

                    b.ToTable("MensajesChat");
                });

            modelBuilder.Entity("ServiHogarConnect.API.Models.Profesional", b =>
                {
                    b.Property<int>("IdProfesional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProfesional"));

                    b.Property<decimal?>("CalificacionPromedio")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<decimal>("TarifaHora")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("IdProfesional");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Profesionales");
                });

            modelBuilder.Entity("ServiHogarConnect.API.Models.SolicitudServicio", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<decimal>("Latitud")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)");

                    b.Property<decimal>("Longitud")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("SolicitudesServicio");
                });

            modelBuilder.Entity("ServiHogarConnect.API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ServiHogarConnect.API.Models.Calificacion", b =>
                {
                    b.HasOne("ServiHogarConnect.API.Models.Profesional", "Profesional")
                        .WithMany("Calificaciones")
                        .HasForeignKey("IdProfesional")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiHogarConnect.API.Models.Usuario", "Usuario")
                        .WithMany("Calificaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profesional");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServiHogarConnect.API.Models.Cotizacion", b =>
                {
                    b.HasOne("ServiHogarConnect.API.Models.Profesional", "Profesional")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("IdProfesional")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiHogarConnect.API.Models.SolicitudServicio", "Solicitud")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesional");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("ServiHogarConnect.API.Models.MensajeChat", b =>
                {
                    b.HasOne("ServiHogarConnect.API.Models.Usuario", "Emisor")
                        .WithMany("MensajesEnviados")
                        .HasForeignKey("IdEmisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiHogarConnect.API.Models.Usuario", "Receptor")
                        .WithMany("MensajesRecibidos")
                        .HasForeignKey("IdReceptor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emisor");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("ServiHogarConnect.API.Models.Profesional", b =>
                {
                    b.HasOne("ServiHogarConnect.API.Models.Usuario", "Usuario")
                        .WithOne("Profesional")
                        .HasForeignKey("ServiHogarConnect.API.Models.Profesional", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServiHogarConnect.API.Models.SolicitudServicio", b =>
                {
                    b.HasOne("ServiHogarConnect.API.Models.CategoriaServicio", "Categoria")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiHogarConnect.API.Models.Usuario", "Usuario")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServiHogarConnect.API.Models.CategoriaServicio", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("ServiHogarConnect.API.Models.Profesional", b =>
                {
                    b.Navigation("Calificaciones");

                    b.Navigation("Cotizaciones");
                });

            modelBuilder.Entity("ServiHogarConnect.API.Models.SolicitudServicio", b =>
                {
                    b.Navigation("Cotizaciones");
                });

            modelBuilder.Entity("ServiHogarConnect.API.Models.Usuario", b =>
                {
                    b.Navigation("Calificaciones");

                    b.Navigation("MensajesEnviados");

                    b.Navigation("MensajesRecibidos");

                    b.Navigation("Profesional");

                    b.Navigation("Solicitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
